### ISSUE TITLE
support "in 2 days" and "2 days ago"

### ISSUE THREAD

**Issue by derhuerst** [fczbkk/parse-relative-time#1]
What do you think about supporting more human formats like `in 2 days` and `2 days ago`? Would you mind a PR?

**Comment by fczbkk** [comment]
Thanks for the idea, @derhuerst. Turns out it was quite easy to implement.

I have created `v1.1.0`, which supports keywords "in" and "ago". So now you can use phrases `in 2 days` or `2 days ago` as input.

Just a warning: Do not mix these keywords with operators. Phrases like `in -2 days` or `+2 days ago` will not work at all.
